export type APP_NAME = 'MPEX_BACKEND';
export type ENDPOINT_STATUS = 'NONE' | 'DELIVERING' | 'DELIVERED' | 'NOT_DELIV' | 'WAREHOUSING';
export const ALL_ENDPOINT_STATUSES: {[t: string]: ENDPOINT_STATUS} = {NONE:'NONE', DELIVERING: 'DELIVERING', DELIVERED: 'DELIVERED', NOT_DELIV: 'NOT_DELIV', WAREHOUSING: 'WAREHOUSING'};
export const ALL_ORDER_STATUSES = { ON_HOLD: 12};

export type TRACKING_STATUS = 'NONE' | 'DELIVERING' | 'DELIVERED' | 'NOT_DELIV' | 'WAREHOUSING';
export const ALL_TRACKING_STATUSES: {[t: string]: TRACKING_STATUS} = {NONE:'NONE', DELIVERING: 'DELIVERING', DELIVERED: 'DELIVERED', NOT_DELIV: 'NOT_DELIV', WAREHOUSING: 'WAREHOUSING'};

export type DRIVER_TYPE = 'INHOUSE' | 'PARTTIME' ;

export type ACCOUNT_TYPE = 1 | 2;
export const ALL_ACCOUNT_TYPE: {[t: string]: ACCOUNT_TYPE} = { MPER: 2, MPEX: 1 };

export type ENDPOINT_TYPE = 0 | 1;
export const ALL_ENDPOINT_TYPE: {[t: string]: ENDPOINT_TYPE} = { DROPOFF: 0, PICKUP: 1 };

export type ONDEMAND_TYPE = 'DN' | 'BFM' | 'DS' | 'NONE';
export const ALL_ONDEMAND_TYPE: {[t: string]: ONDEMAND_TYPE} = { DS: 'DS', BFM: 'BFM', DN: 'DN', NONE: 'NONE' };


export type ROLE = '';

export const REQUEST_TYPE_SAMEDAY = 0;
export const REQUEST_TYPE_ON_DEMAND = 1;